#!/usr/bin/env bash
set -euo pipefail

# Prefer Render's environment variable when it is configured.
# Otherwise keep the checked-in Firebase config generated by GitHub Actions.
if [ -n "\${PULSECHAT_FIREBASE_CONFIG:-}" ]; then
  printf '%s\n' "window.PULSECHAT_FIREBASE_CONFIG = \${PULSECHAT_FIREBASE_CONFIG};" > web/config.js
elif [ ! -f web/config.js ]; then
  printf '%s\n' 'window.PULSECHAT_FIREBASE_CONFIG = null;' > web/config.js
fi

test -f web/index.html
test -f web/app.js
test -f web/styles.css
test -f web/config.js

# Basic JavaScript syntax validation without requiring npm dependencies.
node --check web/app.js
